train:
    _target_: engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
      - _target_: engine.data_preprocessor.BandFilter
      - _target_: engine.data_preprocessor.NormalizeMeanStd
      - _target_: engine.data_preprocessor.BandPadding

val:
    _target_: engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: engine.data_preprocessor.BandFilter
        - _target_: engine.data_preprocessor.NormalizeMeanStd
        - _target_: engine.data_preprocessor.BandPadding

test:
    _target_: engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: engine.data_preprocessor.BandFilter
        - _target_: engine.data_preprocessor.NormalizeMeanStd
        - _target_: engine.data_preprocessor.BandPadding