_target_: encoders.cnn_teacher.SimpleCNNEncoder
#encoder_weights: none
#download_url: https://huggingface.co/chendelong/RemoteCLIP/resolve/main/RemoteCLIP-ViT-B-32.pt

input_bands:
  optical: ['grayscale']


save_feature_maps: false 
output_layers: [1, 2]
input_size: 28
num_blocks : 2
base_channels: 64